server:
    port: 13875
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/studyplatform?charset=utf8mb4&useUnicode=true&serverTimezone=UTC
        username: root
        password: 714825936QY
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
